title: Hong-Phuc Lai
url: "https://laihongphuc.github.io"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

permalink: /blog/:year/:month/:day/:title/

exclude:
  - index_backup.html
  - README.md
